name: Hello!

on: 
  push:
    branches:
      - master
jobs: 
  hello-world:
    runs-on: ubuntu-18.04
    steps:
      - name: print hello
        run: echo "Hello World!"
      - name: show me le date!
        run: date
      - name: show me le files
        run: ls -l
